using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace back.domain.entities
{
    public interface ITGFCAB
    {
        public int nunota { get; set; }
        public short codemp { get; set; }
        public int codcencus { get; set; }
        public int numnota { get; set; }
        public string serienota { get; set; }
        public DateTime dtneg { get; set; }
        public Nullable<DateTime> dtfatur { get; set; }
        public Nullable<DateTime> dtentsai { get; set; }
        public Nullable<DateTime> dtval { get; set; }
        public Nullable<DateTime> dtmov { get; set; }
        public Nullable<DateTime> dtcontab { get; set; }
        public Nullable<int> hrmov { get; set; }
        public short codempnegoc { get; set; }
        public int codparc { get; set; }
        public Nullable<short> codcontato { get; set; }
        public string rateado { get; set; }
        public int codveiculo { get; set; }
        public short codtipoper { get; set; }
        public DateTime dhtipoper { get; set; }
        public string tipmov { get; set; }
        public DateTime dhtipvenda { get; set; }
        public Nullable<int> numcotacao { get; set; }
        public short codvend { get; set; }
        public double comissao { get; set; }
        public short codmoeda { get; set; }
        public short codobspadrao { get; set; }
        public string observacao { get; set; }
        public Nullable<double> vlrseg { get; set; }
        public Nullable<double> vlricmsseg { get; set; }
        public Nullable<double> vlrdestaque { get; set; }
        public Nullable<double> vlrjuro { get; set; }
        public Nullable<double> vlrvendor { get; set; }
        public Nullable<double> vlroutros { get; set; }
        public Nullable<double> vlremb { get; set; }
        public Nullable<double> vlricmsemb { get; set; }
        public Nullable<double> vlrdescserv { get; set; }
        public double ipiemb { get; set; }
        public string tipipiemb { get; set; }
        public Nullable<double> vlrdesctot { get; set; }
        public Nullable<double> vlrdesctotitem { get; set; }
        public Nullable<double> vlrfrete { get; set; }
        public Nullable<double> icmsfrete { get; set; }
        public Nullable<double> baseicmsfrete { get; set; }
        public string tipfrete { get; set; }
        public string cif_fob { get; set; }
        public Nullable<DateTime> vencfrete { get; set; }
        public Nullable<double> vlrnota { get; set; }
        public Nullable<DateTime> vencipi { get; set; }
        public int ordemcarga { get; set; }
        public Nullable<short> seqcarga { get; set; }
        public Nullable<int> kmveiculo { get; set; }
        public int codparctransp { get; set; }
        public Nullable<int> qtdvol { get; set; }
        public string pendente { get; set; }
        public Nullable<double> baseicms { get; set; }
        public Nullable<double> vlricms { get; set; }
        public Nullable<double> baseipi { get; set; }
        public Nullable<double> vlripi { get; set; }
        public string issretido { get; set; }
        public Nullable<double> baseiss { get; set; }
        public Nullable<double> vlriss { get; set; }
        public Nullable<short> codusu { get; set; }
        public string aprovado { get; set; }
        public Nullable<double> vlrirf { get; set; }
        public string irfretido { get; set; }
        public string statusnota { get; set; }
        public Nullable<double> comger { get; set; }
        public string volume { get; set; }
        public int codparcdest { get; set; }
        public double vlrsubst { get; set; }
        public double basesubstit { get; set; }
        public int codproj { get; set; }
        public int numcontrato { get; set; }
        public double baseinss { get; set; }
        public double vlrinss { get; set; }
        public double vlrrepredtot { get; set; }
        public double percdesc { get; set; }
        public int codparcremetente { get; set; }
        public int codparcconsignatario { get; set; }
        public int codparcredespacho { get; set; }
        public string localcoleta { get; set; }
        public string localentrega { get; set; }
        public Nullable<double> vlrmercadoria { get; set; }
        public Nullable<double> peso { get; set; }
        public string notascf { get; set; }
        public int codmoddoc { get; set; }
        public int codnat { get; set; }
        public Nullable<int> codmaq { get; set; }
        public Nullable<int> codfunc { get; set; }
        public Nullable<int> numos { get; set; }
        public Nullable<int> numcf { get; set; }
        public Nullable<double> vlrfretecpl { get; set; }
        public double troco { get; set; }
        public Nullable<short> nroredz { get; set; }
        public Nullable<double> vlrmoeda { get; set; }
        public Nullable<int> occn48 { get; set; }
        public Nullable<short> codusuinc { get; set; }
        public Nullable<int> nutransf { get; set; }
        public Nullable<int> nurd8 { get; set; }
        public Nullable<int> codsite { get; set; }
        public Nullable<double> totalcustoprod { get; set; }
        public Nullable<double> totalcustoserv { get; set; }
        public Nullable<int> codcid { get; set; }
        public Nullable<double> basesubstsemred { get; set; }
        public Nullable<int> codmotorista { get; set; }
        public string naturezaoperdes { get; set; }
        public string serienfdes { get; set; }
        public string modelonfdes { get; set; }
        public short codusucomprador { get; set; }
        public Nullable<DateTime> dtprevent { get; set; }
        public Nullable<int> nunotapedfret { get; set; }
        public Nullable<double> baseirf { get; set; }
        public Nullable<double> aliqirf { get; set; }
        public string placa { get; set; }
        public Nullable<short> ufveiculo { get; set; }
        public Nullable<double> pesobruto { get; set; }
        public Nullable<DateTime> hrentsai { get; set; }
        public string antt { get; set; }
        public string lacres { get; set; }
        public Nullable<int> danfe { get; set; }
        public string chavenfe { get; set; }
        public string numeracaovolumes { get; set; }
        public Nullable<DateTime> dtenviopmb { get; set; }
        public string tipnotapmb { get; set; }
        public Nullable<int> numaleatorio { get; set; }
        public string numprotoc { get; set; }
        public Nullable<DateTime> dhprotoc { get; set; }
        public Nullable<DateTime> dtenvsuf { get; set; }
        public Nullable<int> nulotenfe { get; set; }
        public string statusnfe { get; set; }
        public Nullable<short> tpemisnfe { get; set; }
        public Nullable<DateTime> dtadiam { get; set; }
        public Nullable<int> hradiam { get; set; }
        public Nullable<int> coddoca { get; set; }
        public string digital { get; set; }
        public Nullable<double> totdispdesc { get; set; }
        public Nullable<double> basepis { get; set; }
        public Nullable<double> vlrpis { get; set; }
        public Nullable<double> basepisst { get; set; }
        public Nullable<double> vlrpisst { get; set; }
        public Nullable<double> basecofins { get; set; }
        public Nullable<double> vlrcofins { get; set; }
        public Nullable<double> basecofinsst { get; set; }
        public Nullable<double> vlrcofinsst { get; set; }
        public Nullable<double> vlrroyalt { get; set; }
        public Nullable<int> nrocaixa { get; set; }
        public string numregdpec { get; set; }
        public Nullable<DateTime> dhregdpec { get; set; }
        public Nullable<short> codempfunc { get; set; }
        public Nullable<double> vlrindeniz { get; set; }
        public string marca { get; set; }
        public Nullable<int> tipoptagjnfe { get; set; }
        public Nullable<short> tpemisnfse { get; set; }
        public Nullable<int> nulotenfse { get; set; }
        public string numnfse { get; set; }
        public string statusnfse { get; set; }
        public string ufembarq { get; set; }
        public string locembarq { get; set; }
        public Nullable<short> tpligacao { get; set; }
        public string codgrupotensao { get; set; }
        public Nullable<short> tpassinante { get; set; }
        public string agrupbol { get; set; }
        public Nullable<int> nurem { get; set; }
        public string retdatacritica { get; set; }
        public Nullable<double> qtdbatidas { get; set; }
        public Nullable<double> percpureza { get; set; }
        public Nullable<double> percgermin { get; set; }
        public Nullable<double> fretevlrbruto { get; set; }
        public Nullable<double> fretevlrdesc { get; set; }
        public Nullable<double> fretepercdesc { get; set; }
        public Nullable<double> fretevlrimp { get; set; }
        public Nullable<double> fretevlrjur { get; set; }
        public Nullable<double> fretevlrpago { get; set; }
        public Nullable<short> codvendtec { get; set; }
        public Nullable<int> numpedido { get; set; }
        public Nullable<double> vlrindenizdist { get; set; }
        public Nullable<int> codagenda { get; set; }
        public Nullable<DateTime> dtref { get; set; }
        public Nullable<double> fretevlrnegoc { get; set; }
        public Nullable<int> codprodpermuta { get; set; }
        public Nullable<int> nrogar { get; set; }
        public string md5paf { get; set; }
        public Nullable<int> codmoddocnota { get; set; }
        public string cpfcnpjadquirente { get; set; }
        public string nomeadquirente { get; set; }
        public Nullable<double> vlrsacadolar { get; set; }
        public string numpedido2 { get; set; }
        public Nullable<int> numcoo { get; set; }
        public Nullable<int> ordemcargaant { get; set; }
        public string tpambnfe { get; set; }
        public Nullable<int> przmed { get; set; }
        public Nullable<int> codresiduo { get; set; }
        public Nullable<DateTime> dtref2 { get; set; }
        public string vlrliqitemnfe { get; set; }
        public string clascons { get; set; }
        public Nullable<int> numform { get; set; }
        public Nullable<DateTime> dtref3 { get; set; }
        public Nullable<int> codcc { get; set; }
        public string produetloc { get; set; }
        public Nullable<double> vlrstextranotatot { get; set; }
        public Nullable<int> nutranemp { get; set; }
        public string sitespecialresp { get; set; }
        public Nullable<DateTime> dtentsaiinfo { get; set; }
        public string exigeissqn { get; set; }
        public string regesptribut { get; set; }
        public string motnaoreterissqn { get; set; }
        public Nullable<DateTime> dtremret { get; set; }
        public string libconf { get; set; }
        public Nullable<int> nuconfatual { get; set; }
        public string statusxtrategie { get; set; }
        public Nullable<int> codsaf { get; set; }
        public Nullable<double> vlrfretecalc { get; set; }
        public Nullable<double> vlrjurodist { get; set; }
        public string notaempenho { get; set; }
        public Nullable<int> codtpd { get; set; }
        public Nullable<int> codvtp { get; set; }
        public string cancelado { get; set; }
        public string pesobrutomanual { get; set; }
        public string pesoliquimanual { get; set; }
        public Nullable<int> nupca { get; set; }
        public string indpresnfce { get; set; }
        public Nullable<double> m3 { get; set; }
        public Nullable<double> vlrtotliqitemmoe { get; set; }
        public double vlrdesctotitemmoe { get; set; }
        public string chavecte { get; set; }
        public string prodpred { get; set; }
        public Nullable<short> tpemiscte { get; set; }
        public string tpambcte { get; set; }
        public string lotacao { get; set; }
        public string statuscte { get; set; }
        public Nullable<int> numaleatoriocte { get; set; }
        public string numprotoccte { get; set; }
        public Nullable<DateTime> dhprotoccte { get; set; }
        public Nullable<int> nulotecte { get; set; }
        public Nullable<DateTime> dtdeclara { get; set; }
        public Nullable<int> reboque1 { get; set; }
        public Nullable<int> reboque2 { get; set; }
        public Nullable<int> reboque3 { get; set; }
        public string situacaocte { get; set; }
        public string ctelotacao { get; set; }
        public Nullable<int> codveitracao { get; set; }
        public string codobra { get; set; }
        public string codart { get; set; }
        public Nullable<int> idiproc { get; set; }
        public string viatransp { get; set; }
        public string tipprocimp { get; set; }
        public string cnpjadquirente { get; set; }
        public string ufadquirente { get; set; }
        public Nullable<DateTime> dhemissepec { get; set; }
        public Nullable<int> nunotasub { get; set; }
        public string chavenfse { get; set; }
        public string modentrega { get; set; }
        public Nullable<double> vlricmsdifaldest { get; set; }
        public Nullable<double> vlricmsdifalrem { get; set; }
        public Nullable<decimal> ciot { get; set; }
        public Nullable<double> vlrfretetotal { get; set; }
        public Nullable<int> codparctranspfinal { get; set; }
        public Nullable<double> vlricmsfcp { get; set; }
        public string fusoemissepec { get; set; }
        public Nullable<double> vlrdescrat { get; set; }
        public string chavenferef { get; set; }
        public Nullable<int> seqconfirma { get; set; }
        public Nullable<int> codcontatoentrega { get; set; }
        public Nullable<int> codcidorigem { get; set; }
        public Nullable<int> codciddestino { get; set; }
        public Nullable<int> codcidentrega { get; set; }
        public Nullable<short> coduforigem { get; set; }
        public Nullable<short> codufdestino { get; set; }
        public Nullable<short> codufentrega { get; set; }
        public string classificms { get; set; }
        public Nullable<short> nufop { get; set; }
        public string codrastreamentoect { get; set; }
        public Nullable<int> nuodp { get; set; }
        public Nullable<int> nupedfrete { get; set; }
        public Nullable<int> codcidprest { get; set; }
        public string formpgtcte { get; set; }
        public Nullable<double> percdescfob { get; set; }
        public string tpambnfse { get; set; }
        public string termacordnota { get; set; }
        public Nullable<double> vlrdescqtd { get; set; }
        public Nullable<double> vlricmsfcpint { get; set; }
        public Nullable<double> vlrstfcpint { get; set; }
        public Nullable<double> vlrstfcpintant { get; set; }
        public string cteglobal { get; set; }
        public Nullable<double> vlrcargaaverb { get; set; }
        public Nullable<int> codcidinicte { get; set; }
        public Nullable<int> codcidfimcte { get; set; }
        public Nullable<int> nucfr { get; set; }
        public string ad_status { get; set; }
        public Nullable<double> ad_perccom { get; set; }
        public string ad_observacao { get; set; }
        public Nullable<int> ad_nurevp { get; set; }
        public Nullable<double> vlrprestafrmm { get; set; }
        public Nullable<double> vlrafrmm { get; set; }
        public string idnavio { get; set; }
        public string irinnavio { get; set; }
        public string direcaoviag { get; set; }
        public string idbalsa01 { get; set; }
        public string idbalsa02 { get; set; }
        public string idbalsa03 { get; set; }
        public string nfedevrecusa { get; set; }
        public string agrupfinnota { get; set; }
        public Nullable<int> ad_nuprog { get; set; }
        public Nullable<double> ad_vlracresdec { get; set; }
        public string confirmnotafat { get; set; }
        public string ad_ligarantes { get; set; }
        public Nullable<int> ad_pedidoid { get; set; }
        public string permaltercentral { get; set; }
        public Nullable<short> codguf { get; set; }
        public Nullable<int> ad_nunota { get; set; }
        public string ad_redp { get; set; }
        public string ad_redp_razao { get; set; }
        public string ad_redp_cnpj { get; set; }
        public string ad_redp_tel { get; set; }
        public Nullable<double> ad_vlrfretecalc { get; set; }
        public Nullable<int> ad_nunotaconf { get; set; }
        public string ad_classepedido { get; set; }
        public Nullable<double> ad_vlrfretetotal { get; set; }
        public Nullable<double> ad_vlrseg2 { get; set; }
        public Nullable<double> ad_vlrfretepf { get; set; }
        public string ad_comprador { get; set; }
        public Nullable<int> ad_nusoldev { get; set; }
        public Nullable<int> esu_bkp_pendente { get; set; }
        public string esu_bkp_pendente_dois { get; set; }
        public Nullable<DateTime> ad_dt_confirmacao { get; set; }
        public Nullable<double> ad_calccommanual { get; set; }
        public Nullable<double> vlrrepredtotsemdesc { get; set; }
        public string ad_temremessa { get; set; }
        public string finalizadofox { get; set; }
        public string ad_novocliente_cnpj { get; set; }
        public Nullable<int> ad_numped_mercos { get; set; }
        public Nullable<int> numcupomeconect { get; set; }
        public Nullable<int> ad_pedidoidfotus { get; set; }
        public string ad_integrador { get; set; }
        public Nullable<double> ad_promvendas { get; set; }
        public Nullable<DateTime> dtextempk280 { get; set; }
        public Nullable<int> timnufinorig { get; set; }
        public Nullable<int> timcontratovenda { get; set; }
        public string timorigem { get; set; }
        public Nullable<int> timcontratoltv { get; set; }
        public Nullable<int> timnunotamod { get; set; }
        public Nullable<int> ad_nunota_ld { get; set; }
        public string ad_nova_conf { get; set; }
        public Nullable<DateTime> ad_dt_nova_conf { get; set; }
        public Nullable<double> ad_freteint { get; set; }
        public Nullable<double> ad_perccomcompra { get; set; }
        public Nullable<double> ad_taxaexport { get; set; }
        public Nullable<int> ad_nrocrm { get; set; }
        public string latitude { get; set; }
        public string longitude { get; set; }
        public Nullable<double> ad_totnotayuan { get; set; }
        public Nullable<int> codparcdescargamdfe { get; set; }
        public Nullable<short> coddocarrecad { get; set; }
        public string numdocarrecad { get; set; }
        public string premiacaoestadual { get; set; }
        public Nullable<int> ad_pedidoidfotusorig { get; set; }
        public Nullable<int> ad_codparcred { get; set; }
        public Nullable<int> ad_codparc { get; set; }
        public string ad_obsnfered { get; set; }
        public string nfseid { get; set; }
        public string ad_vendadireta { get; set; }
        public string ad_cotar_frete { get; set; }
        public Nullable<DateTime> ad_dhenvcotfrete { get; set; }
        public Nullable<int> ad_codsacf { get; set; }
        public Nullable<int> codparcdepo { get; set; }
        public string ad_embalagem { get; set; }
        public string ad_temadiantamento { get; set; }
        public Nullable<int> codcheckout { get; set; }
        public Nullable<int> ad_codinv { get; set; }
        public Nullable<int> ad_codsinist { get; set; }
        public Nullable<double> ad_potencia_ger { get; set; }
        public Nullable<DateTime> ad_database { get; set; }
        public Nullable<int> ad_pvfnrofotusorig { get; set; }
        public Nullable<int> ad_pvfnrofotusseq { get; set; }
        public string ad_pvfmotivodupl { get; set; }
        public string ad_pvfnovoproc { get; set; }
        public Nullable<double> vlrfethab { get; set; }
        public Nullable<double> baseicmsat { get; set; }
        public Nullable<double> vlricmsat { get; set; }
        public Nullable<double> valordesonpiscofins { get; set; }
        public string disdesautimpemb { get; set; }
        public Nullable<int> nunotaorigcorte { get; set; }
        public string ad_ordemcompra { get; set; }
        public Nullable<DateTime> ad_dtfat { get; set; }
        public string ad_temordemcomp { get; set; }
        public string ad_temdtfat { get; set; }
        public Nullable<int> ad_boldiasvenc { get; set; }
        public Nullable<DateTime> ad_dtcartao { get; set; }
        public Nullable<int> codinterm { get; set; }
        public string intermed { get; set; }
        public Nullable<double> vlrrepredst { get; set; }
        public Nullable<double> baseicmsstfrete { get; set; }
        public Nullable<double> icmsstfrete { get; set; }
        public Nullable<decimal> iddescparceria { get; set; }
        public Nullable<decimal> vlrdescparceria { get; set; }
        public Nullable<decimal> clienteidparceria { get; set; }
        public Nullable<decimal> idpontuacaoparceria { get; set; }
        public string fistel { get; set; }
        public Nullable<int> numcstc { get; set; }
        public Nullable<int> qtdusu { get; set; }
        public Nullable<int> numtermtel { get; set; }
        public Nullable<short> tipclienteservcom { get; set; }
        public string md5modcomtel { get; set; }
        public string indnegmodal { get; set; }
        public Nullable<int> codparcretirada { get; set; }
        public short codtipvenda { get; set; }
        public DateTime dtalter { get; set; }

    }
}