using System;

namespace back.domain.entities
{
    public interface ITGFPAR
    {
        public short codvend { get; set; }
        public string nomeparc { get; set; }
        public string razaosocial { get; set; }
        public char tippessoa { get; set; }
        public Nullable<int> codparcmatriz { get; set; }
        public int codend { get; set; }
        public string numend { get; set; }
        public string complemento { get; set; }
        public int codbai { get; set; }
        public int codcid { get; set; }
        public string cep { get; set; }
        public string caixapostal { get; set; }
        public string telefone { get; set; }
        public Nullable<short> ramal { get; set; }
        public string fax { get; set; }
        public string email { get; set; }
        public string identinscestad { get; set; }
        public string inscestadnauf { get; set; }
        public string cgc_cpf { get; set; }
        public Nullable<decimal> limcred { get; set; }
        public string cliente { get; set; }
        public string classificms { get; set; }

        public int codreg { get; set; }
        public DateTime dtcad { get; set; }
        public DateTime dtalter { get; set; }
        public Nullable<DateTime> dtnasc { get; set; }
        public Nullable<DateTime> dtultcontato { get; set; }
        public Nullable<DateTime> dtultnegoc { get; set; }
        public Nullable<short> codtab { get; set; }
        public Nullable<short> prazocontato { get; set; }
        public Nullable<short> prazopag { get; set; }
        public Nullable<short> tolerinadimp { get; set; }
        public string fornecedor { get; set; }
        public string transportadora { get; set; }
        public string vendedor { get; set; }
        public string agencia { get; set; }
        public int codtipparc { get; set; }
        public string codctabco { get; set; }
        public string codage { get; set; }
        public short codbco { get; set; }
        public string nomeage { get; set; }
        public Nullable<int> codctactb { get; set; }
        public Nullable<int> codctactb2 { get; set; }
        public string tare { get; set; }
        public string ipiincicms { get; set; }
        public string retemiss { get; set; }
        public string reteminss { get; set; }
        public string contacesso { get; set; }
        public string situacao { get; set; }
        public string observacoes { get; set; }
        public string ativo { get; set; }
        public Nullable<int> codant { get; set; }
        public Nullable<short> codctabcoint { get; set; }
        public string grupoautor { get; set; }
        public string bloquear { get; set; }
        public string selecionado { get; set; }
        public string motbloq { get; set; }
        public string evenda { get; set; }
        public string ecompra { get; set; }
        public string homepage { get; set; }
        public string ctaadiant { get; set; }
        public short codassessor { get; set; }
        public string inscmun { get; set; }
        public string calcinss { get; set; }
        public short codusu { get; set; }
        public string retempis { get; set; }
        public string retemcofins { get; set; }
        public string retemcsl { get; set; }
        public string usuario { get; set; }
        public Nullable<decimal> limcredmensal { get; set; }
        public string cei { get; set; }
        public Nullable<short> codtabst { get; set; }
        public Nullable<short> qtdmaxtitvencidos { get; set; }
        public string temipi { get; set; }
        public string aluno { get; set; }
        public string professor { get; set; }
        public Nullable<double> descfin { get; set; }
        public string descbonif { get; set; }
        public string implaudolote { get; set; }
        public Nullable<short> diasem { get; set; }
        public string medico { get; set; }
        public string tipofatur { get; set; }
        public Nullable<short> diasvarpagto { get; set; }
        public string codunimed { get; set; }
        public Nullable<int> codcred { get; set; }
        public Nullable<double> perccusvar { get; set; }
        public string motorista { get; set; }
        public string naturezaoperdes { get; set; }
        public string serienfdes { get; set; }
        public string modelonfdes { get; set; }
        public string descstiva { get; set; }
        public Nullable<short> cstipient { get; set; }
        public Nullable<short> cstipisai { get; set; }
        public Nullable<short> codemp { get; set; }
        public Nullable<double> vlrminpedcpa { get; set; }
        public Nullable<int> qtdmaxpedcpa { get; set; }
        public string operlogist { get; set; }
        public string agronomo { get; set; }
        public string produtortemnf { get; set; }
        public Nullable<double> potencialneg { get; set; }
        public string ordsubst { get; set; }
        public Nullable<double> maxcredindeniz { get; set; }
        public Nullable<double> maxdebindeniz { get; set; }
        public Nullable<double> saldoindeniz { get; set; }
        public string flex { get; set; }
        public string simples { get; set; }
        public string emailnfe { get; set; }
        public string tipanexonfe { get; set; }
        public string sexo { get; set; }
        public Nullable<int> nurespperg { get; set; }
        public Nullable<int> nuresppergfech { get; set; }
        public Nullable<int> codrota { get; set; }
        public Nullable<int> codctactb3 { get; set; }
        public Nullable<int> codctactb4 { get; set; }
        public short codusucobr { get; set; }
        public string agrupar { get; set; }
        public string emaildanfe { get; set; }
        public string valdescgrdcar { get; set; }
        public string agrupbolempdif { get; set; }
        public Nullable<double> percredinss { get; set; }
        public string permitecorte { get; set; }
        public string indnatret { get; set; }
        public string statusedz { get; set; }
        public string sitreceita { get; set; }
        public string sitsintegra { get; set; }
        public string sitccf { get; set; }
        public string usatabcrforn { get; set; }
        public Nullable<int> qtdpedprzmed { get; set; }
        public Nullable<int> diaspedprzmed { get; set; }
        public string artprecad { get; set; }
        public string gerctrcauto { get; set; }
        public short codlocalpadrao { get; set; }
        public Nullable<double> saldodisp { get; set; }
        public Nullable<double> provacresc { get; set; }
        public string exigelaudoprd { get; set; }
        public string meirj { get; set; }
        public string entregaendcontato { get; set; }
        public Nullable<short> codempparc { get; set; }
        public string retstvenda { get; set; }
        public string latitude { get; set; }
        public string longitude { get; set; }
        public string tipogerboleto { get; set; }
        public Nullable<double> percjuro { get; set; }
        public Nullable<double> percmulta { get; set; }
        public string tipjuro { get; set; }
        public Nullable<double> percdescespecial { get; set; }
        public Nullable<short> codemppref { get; set; }
        public string sitespecialresp { get; set; }
        public string motnaoreterissqn { get; set; }
        public Nullable<short> sitcadsefaz { get; set; }
        public Nullable<DateTime> dhcadsefaz { get; set; }
        public Nullable<double> aliqissretsimples { get; set; }
        public string idestrangeiro { get; set; }
        public string tipgerbolcent { get; set; }
        public string tipogerboletodup { get; set; }
        public string boldestemail { get; set; }
        public string comoconheceu { get; set; }
        public Nullable<short> tpassinante { get; set; }
        public string aplicleitransp { get; set; }
        public Nullable<double> vendamin { get; set; }
        public Nullable<short> codenqipient { get; set; }
        public Nullable<short> codenqipisai { get; set; }
        public string envipedemailtop { get; set; }
        public string integraeconect { get; set; }
        public string senhaeconect { get; set; }
        public string prazoparceconect { get; set; }
        public short baseprazoeconect { get; set; }
        public string parcelameconect { get; set; }
        public short baseparceleconect { get; set; }
        public Nullable<short> diafechaeconect { get; set; }
        public Nullable<short> diapagtoeconect { get; set; }
        public string perfileconect { get; set; }
        public Nullable<DateTime> dtemisnfeforn { get; set; }
        public string estabtransp { get; set; }
        public string transppropria { get; set; }
        public string termacord { get; set; }
        public Nullable<int> intervanaliscred { get; set; }
        public string indcomercializacao { get; set; }
        public string indaquisicao { get; set; }
        public string emailnotifentrega { get; set; }
        public string impagrupfin { get; set; }
        public Nullable<short> tiplotacao { get; set; }
        public Nullable<short> unidimport { get; set; }
        public Nullable<double> merchantid { get; set; }
        public Nullable<int> ad_codant { get; set; }
        public Nullable<int> ad_codveiculo { get; set; }
        public Nullable<int> codparcgrueconomico { get; set; }
        public string enqart227 { get; set; }
        public Nullable<double> limcheqeconect { get; set; }
        public string orgpublnfse { get; set; }
        public Nullable<int> ad_diasanafin { get; set; }
        public string associacaodesp { get; set; }
        public Nullable<int> modelonotacompra { get; set; }
        public string ad_pontualidade { get; set; }
        public string cpfprodrural { get; set; }
        public Nullable<int> ad_codempant { get; set; }
        public Nullable<int> ad_codclassicms { get; set; }
        public string vlrliqitemnfe { get; set; }
        public string vlrliqitemnfce { get; set; }
        public string arredprimeiraparc { get; set; }
        public Nullable<DateTime> dhcadrf { get; set; }
        public Nullable<short> sitcadrf { get; set; }
        public string emailnfse { get; set; }
        public Nullable<short> nufop { get; set; }
        public string cnae { get; set; }
        public Nullable<short> indcrednfe { get; set; }
        public Nullable<short> indcredcte { get; set; }
        public Nullable<DateTime> dtiniativ { get; set; }
        public Nullable<DateTime> dtultsit { get; set; }
        public Nullable<DateTime> dtbaixa { get; set; }
        public string regapur { get; set; }
        public Nullable<int> codgrupo { get; set; }
        public string parcinter { get; set; }
        public Nullable<short> indopccp { get; set; }
        public Nullable<short> codcontatopadcot { get; set; }
        public string truncparcela { get; set; }
        public string ad_end_validado { get; set; }
        public string ad_icms_validado { get; set; }
        public string ad_lib_proposta { get; set; }
        public Nullable<int> nuversao { get; set; }
        public string ad_nao_env_banco { get; set; }
        public string timestadocivil { get; set; }
        public string timquercomprar { get; set; }
        public string timreferencia02 { get; set; }
        public string timorgao { get; set; }
        public string timcomprador { get; set; }
        public Nullable<int> timbairrocompra { get; set; }
        public Nullable<DateTime> timdataci { get; set; }
        public string timpropvenda { get; set; }
        public string timpai { get; set; }
        public string timreferencia01 { get; set; }
        public string timtipomoradia { get; set; }
        public string timinquilino { get; set; }
        public string timtelefone02 { get; set; }
        public string timproprieta { get; set; }
        public string timcorrespbancario { get; set; }
        public string timmae { get; set; }
        public string timfaixasalarial { get; set; }
        public string timcorretor { get; set; }
        public string timouttels { get; set; }
        public string timtelefone01 { get; set; }
        public Nullable<double> timainvestir { get; set; }
        public string timfiador { get; set; }
        public string timsenhasite { get; set; }
        public string timsenhadesc { get; set; }
        public Nullable<int> timcartorio { get; set; }
        public Nullable<int> timprofissao { get; set; }
        public Nullable<short> timnacionalidad { get; set; }
        public string timcartregimebensv { get; set; }
        public string ad_cad_vendedor { get; set; }
        public Nullable<int> ad_cad_codvend { get; set; }
        public string ad_cadcrm { get; set; }
        public string inscrcno { get; set; }
        public string parcsubstiss { get; set; }
        public string exigcontatoentcab { get; set; }
        public string enviadanferedespacho { get; set; }
        public string ad_integrador { get; set; }
        public string exigenomeparc { get; set; }
        public string ad_cadvend_validado { get; set; }
        public string ad_classcom { get; set; }
        public string ad_classfin { get; set; }
        public Nullable<double> saldodispcac { get; set; }
        public Nullable<double> provacresccac { get; set; }
        public string considtotitenstrib { get; set; }
        public string ad_libfotus { get; set; }
        public string ad_key_account { get; set; }
        public string desconsidescbase { get; set; }
        public string atunuversao { get; set; }
        public string ad_dadosbancimp { get; set; }
        public string ad_cttinstremb { get; set; }
        public Nullable<double> ad_saldoant { get; set; }
        public string ad_ufimp { get; set; }
        public Nullable<int> codidentcons { get; set; }
        public string utilizanucadparc { get; set; }
        public Nullable<short> tipclienteservcom { get; set; }
        public string ad_nomecontato { get; set; }
        public string ad_solicitresc { get; set; }
        public string chavepix { get; set; }

    }
}