using System;

namespace back.domain.entities
{
    public interface ITGFPRO
    {
        public int CodProd { get; set; }
        public String Descrprod { get; set; }
        public String Compldesc { get; set; }
        public String Caracteristicas { get; set; }
        public String Referencia { get; set; }
        public int Codgrupoprod { get; set; }
        public String Codvol { get; set; }
        public String Marca { get; set; }
        public String Localizacao { get; set; }
        public Nullable<short> Codipi { get; set; }
        public Nullable<short> Classubtrib { get; set; }
        public Nullable<short> Codformprec { get; set; }
        public Nullable<Double> Marglucro { get; set; }
        public Nullable<Double> Multipvenda { get; set; }
        public Nullable<short> Deccusto { get; set; }
        public Nullable<short> Decvlr { get; set; }
        public Nullable<short> Decqtd { get; set; }
        public Nullable<Double> Comger { get; set; }
        public Nullable<Double> Comvend { get; set; }
        public Nullable<Double> Descmax { get; set; }
        public Decimal Pesobruto { get; set; }
        public Decimal Pesoliq { get; set; }
        public Nullable<Double> Medaux { get; set; }
        public Nullable<short> Prazoval { get; set; }
        public Nullable<Decimal> Agrupmin { get; set; }
        public Nullable<short> Qtdemb { get; set; }
        public String Alertaestmin { get; set; }
        public String Promocao { get; set; }
        public String Temicms { get; set; }
        public String Temiss { get; set; }
        public String Temipivenda { get; set; }
        public String Temipicompra { get; set; }
        public String Temirf { get; set; }
        public Nullable<Double> Percirf { get; set; }
        public String Teminss { get; set; }
        public Double Percinss { get; set; }
        public Double Redbaseinss { get; set; }
        public String Usoprod { get; set; }
        public String Origprod { get; set; }
        public String Tipsubst { get; set; }
        public Nullable<Double> Codicmsfast { get; set; }
        public String Tiplancnota { get; set; }
        public String Tipcontest { get; set; }
        public Nullable<short> Codtab { get; set; }
        public Nullable<int> Codctactb { get; set; }
        public Byte[] Imagem { get; set; }
        public String Ativo { get; set; }
        public Nullable<Double> Estmax { get; set; }
        public Nullable<Double> Estmin { get; set; }
        public String Apresdetalhe { get; set; }
        public String Selecionado { get; set; }
        public String Titcontest { get; set; }
        public String Liscontest { get; set; }
        public Nullable<int> Grupoicms { get; set; }
        public Nullable<Decimal> Percaumentcusto { get; set; }
        public String Local { get; set; }
        public short Codmoeda { get; set; }
        public DateTime Dtalter { get; set; }
        public String Usalocal { get; set; }
        public String Homepage { get; set; }
        public Nullable<int> Codctactb2 { get; set; }
        public Nullable<int> Codctactb3 { get; set; }
        public Nullable<DateTime> Temposerv { get; set; }
        public String Endimagem { get; set; }
        public short Codusu { get; set; }
        public Nullable<int> Codparcforn { get; set; }
        public String Codvolcompra { get; set; }
        public String Codprodroi { get; set; }
        public String Grupodescprod { get; set; }
        public String Refforn { get; set; }
        public String Hrdobrada { get; set; }
        public String Icmsgerencia { get; set; }
        public int Codnat { get; set; }
        public int Codcencus { get; set; }
        public int Codproj { get; set; }
        public Nullable<Double> M3 { get; set; }
        public String Temciap { get; set; }
        public String Implaudolote { get; set; }
        public Nullable<int> Codgar { get; set; }
        public Nullable<int> Codctactb4 { get; set; }
        public String Dimensoes { get; set; }
        public Nullable<Double> Percquebratec { get; set; }
        public Nullable<short> Codfiltro { get; set; }
        public String Endmodrotulo { get; set; }
        public Nullable<int> Codgenero { get; set; }
        public Nullable<int> Codlst { get; set; }
        public String Padrao { get; set; }
        public String Naturezaoperdes { get; set; }
        public Nullable<int> Cnae { get; set; }
        public String Solcompra { get; set; }
        public String Confere { get; set; }
        public String Remeter { get; set; }
        public String Motivoincexc { get; set; }
        public Nullable<Decimal> Arredpreco { get; set; }
        public String Temcomissao { get; set; }
        public String Componobrig { get; set; }
        public String Fattotal { get; set; }
        public String Nometab { get; set; }
        public String Ap1rctego { get; set; }
        public String Calculogiro { get; set; }
        public Nullable<Double> Redbaseirf { get; set; }
        public Nullable<Double> Altura { get; set; }
        public Nullable<Double> Largura { get; set; }
        public Nullable<Double> Espessura { get; set; }
        public String Unidade { get; set; }
        public Nullable<short> Codformaponta { get; set; }
        public Nullable<short> Codcos { get; set; }
        public String Confcegapeso { get; set; }
        public Nullable<short> Ordcalccustprod { get; set; }
        public String Regrawms { get; set; }
        public String Grupopis { get; set; }
        public String Grupocofins { get; set; }
        public String Grupocssl { get; set; }
        public Nullable<short> Cstipient { get; set; }
        public Nullable<short> Cstipisai { get; set; }
        public String Statusincexc { get; set; }
        public String Utilizawms { get; set; }
        public String Balanca { get; set; }
        public Nullable<short> Codpais { get; set; }
        public String Rendimento { get; set; }
        public String Obsetiqueta { get; set; }
        public Nullable<int> Codanp { get; set; }
        public String Codautcodif { get; set; }
        public Nullable<int> Codprodagrupapt { get; set; }
        public Nullable<int> Codprodagrupaptenc { get; set; }
        public String Cultura { get; set; }
        public String Cientifico { get; set; }
        public Nullable<int> Classeagt { get; set; }
        public Nullable<int> Grupoquimico { get; set; }
        public Nullable<int> Classetox { get; set; }
        public Nullable<int> Princativo { get; set; }
        public String Formulacao { get; set; }
        public String Concentracao { get; set; }
        public String Modoaplic { get; set; }
        public String Epocaaplic { get; set; }
        public String Manejoint { get; set; }
        public Nullable<Double> Dosagem { get; set; }
        public String Voldosagem { get; set; }
        public Nullable<Double> Dosagempor { get; set; }
        public String Voldosagempor { get; set; }
        public String Rendimentopr { get; set; }
        public String Receituario { get; set; }
        public String Exigebenefic { get; set; }
        public String Tipoclasseagt { get; set; }
        public String Tipogrupoquimico { get; set; }
        public String Tipoprincativo { get; set; }
        public String Tipoclassetox { get; set; }
        public Nullable<int> Grupotransg { get; set; }
        public String Geraplaprod { get; set; }
        public Nullable<int> Aplicacao { get; set; }
        public Nullable<int> intervalo { get; set; }
        public Nullable<int> Carencia { get; set; }
        public Nullable<Double> Rendimentoha { get; set; }
        public short Produtonfe { get; set; }
        public short Tipgtinnfe { get; set; }
        public String Ncm { get; set; }
        public String Codvolplan { get; set; }
        public Nullable<Double> Descmaxflex { get; set; }
        public Nullable<Double> Acrescmax { get; set; }
        public String Flex { get; set; }
        public Nullable<int> Numitemrea { get; set; }
        public String Imprimir { get; set; }
        public String Confirmaimp { get; set; }
        public String Apuraprodepe { get; set; }
        public String Indespprodepe { get; set; }
        public int Qtdnflaudosint { get; set; }
        public String Codtribmuniss { get; set; }
        public String Tipcontestwms { get; set; }
        public String Listalpm { get; set; }
        public String Oneroso { get; set; }
        public String Refmercmed { get; set; }
        public String Termolabil { get; set; }
        public Nullable<Double> Tempminima { get; set; }
        public Nullable<Double> Tempmaxima { get; set; }
        public String Controlado { get; set; }
        public String Idenportaria { get; set; }
        public String Idenotc { get; set; }
        public String Idencorrelato { get; set; }
        public String Idencosme { get; set; }
        public String Prodfalta { get; set; }
        public Nullable<int> Codfab { get; set; }
        public int Statusmed { get; set; }
        public Nullable<int> Codcpr { get; set; }
        public Nullable<short> Seqspr { get; set; }
        public Nullable<short> Seqsca { get; set; }
        public Nullable<short> Seqste { get; set; }
        public Nullable<int> Codcat { get; set; }
        public Nullable<int> Codter { get; set; }
        public Nullable<int> Codpat { get; set; }
        public Double Mvaajustado { get; set; }
        public String Infpureza { get; set; }
        public String Fabricante { get; set; }
        public String Usastatuslote { get; set; }
        public Nullable<short> Tamlote { get; set; }
        public Nullable<short> Tamserie { get; set; }
        public String Unidminarmaz { get; set; }
        public String Origemfat { get; set; }
        public String Usacodbarrasqtd { get; set; }
        public String Md5paf { get; set; }
        public String Valcapm3 { get; set; }
        public String Qtdpecafrac { get; set; }
        public String Utilordcorte { get; set; }
        public Nullable<int> Codprodperda { get; set; }
        public String Descrutilbem { get; set; }
        public String Impordemcorte { get; set; }
        public Double Perctroca { get; set; }
        public Nullable<int> Corfontconspreco { get; set; }
        public Nullable<int> Corfundoconspreco { get; set; }
        public String Codvolres { get; set; }
        public Nullable<int> Codareasep { get; set; }
        public Nullable<short> Identimob { get; set; }
        public Nullable<short> Utilimob { get; set; }
        public String Temcredpiscofinsdepr { get; set; }
        public Nullable<int> Codprodinnatura { get; set; }
        public String Utilsmartcard { get; set; }
        public String Recupavaria { get; set; }
        public Nullable<Double> Convervol { get; set; }
        public Nullable<int> Lastro { get; set; }
        public Nullable<int> Camadas { get; set; }
        public Nullable<Double> Ordemmedida { get; set; }
        public Nullable<Double> Aliqicmsintefd { get; set; }
        public String Codregmapa { get; set; }
        public String Apresform { get; set; }
        public String Codbarcomp { get; set; }
        public String Temmedicao { get; set; }
        public Nullable<short> Codfiltroreq { get; set; }
        public String Natbcpiscofins { get; set; }
        public String Contarporpeso { get; set; }
        public Nullable<int> Codlocalpadrao { get; set; }
        public String Permcompprod { get; set; }
        public short Codexncm { get; set; }
        public int Qtdcst { get; set; }
        public int Diascst { get; set; }
        public int Perctolvarcst { get; set; }
        public Nullable<Double> Qtdpedpend { get; set; }
        public Nullable<int> Leadtime { get; set; }
        public String Valcbglobal { get; set; }
        public String Usapontos { get; set; }
        public Nullable<int> Codrfa { get; set; }
        public Nullable<Decimal> Percroyalty { get; set; }
        public String integraeconect { get; set; }
        public Nullable<int> Shelflife { get; set; }
        public Nullable<int> Shelflifemin { get; set; }
        public String Dtvaldif { get; set; }
        public String Enqreintegra { get; set; }
        public Nullable<int> Diasexpedicao { get; set; }
        public String Codbarbalanca { get; set; }
        public Double Perccmtnac { get; set; }
        public Double Perccmtimp { get; set; }
        public String Notifconf { get; set; }
        public String Usaseriefab { get; set; }
        public String Tipsernfe { get; set; }
        public String Vencompindiv { get; set; }
        public String Excluirconf { get; set; }
        public String Produzaut { get; set; }
        public String Usaimpagrupmin { get; set; }
        public String Rastrestoque { get; set; }
        public String Impetiqconf { get; set; }
        public Nullable<Double> Vlrcomerc { get; set; }
        public Nullable<Double> Vlrparcimpext { get; set; }
        public String Codfci { get; set; }
        public String Codativreintegra { get; set; }
        public String Servparaindust { get; set; }
        public String Cat1799spres { get; set; }
        public Nullable<Double> Aliqnac { get; set; }
        public Nullable<Double> Aliqimp { get; set; }
        public String Descrprodnfe { get; set; }
        public String Geracustcompseg { get; set; }
        public Double Estsegqtd { get; set; }
        public Nullable<short> Estsegdias { get; set; }
        public Nullable<DateTime> Dtalteresq { get; set; }
        public Nullable<short> Lotecompras { get; set; }
        public Double Estmaxqtd { get; set; }
        public Nullable<short> Estmaxdias { get; set; }
        public Nullable<DateTime> Dtalteremq { get; set; }
        public Double Desviomax { get; set; }
        public Double Arredagrup { get; set; }
        public String Aplicasazo { get; set; }
        public Double Lotecompminimo { get; set; }
        public Double Agrupcompminimo { get; set; }
        public String Usaseriesepwms { get; set; }
        public Nullable<int> Codgprod { get; set; }
        public Nullable<int> Codparcconsig { get; set; }
        public Nullable<short> Topfaturcon { get; set; }
        public String Serfaturcon { get; set; }
        public String Usalotedtval { get; set; }
        public String Usalotedtfab { get; set; }
        public String Exigelastrocamadas { get; set; }
        public String Fixoagenda { get; set; }
        public String Exibcompexpkit { get; set; }
        public Nullable<short> Tiporeceitamod21 { get; set; }
        public Nullable<short> Natefdcontm410m810 { get; set; }
        public Nullable<int> Codprodsubst { get; set; }
        public Nullable<DateTime> Dtsubst { get; set; }
        public Nullable<int> Codcomp { get; set; }
        public Nullable<Double> Perctolpesomaior { get; set; }
        public Nullable<Double> Perctolpesomenor { get; set; }
        public String Codvolpesovar { get; set; }
        public String Usacontpesovar { get; set; }
        public Nullable<Double> Perctolpesomaiorsep { get; set; }
        public Nullable<Double> Perctolpesomenorsep { get; set; }
        public Nullable<Double> Pct_Bf { get; set; }
        public Nullable<short> Prz_Bf { get; set; }
        public String Controlmedic { get; set; }
        public Nullable<short> Decvlrent { get; set; }
        public Double Perccmtfed { get; set; }
        public Double Perccmtest { get; set; }
        public Double Perccmtmun { get; set; }
        public String Descvenconsul { get; set; }
        public Nullable<int> Grupoicms2 { get; set; }
        public Nullable<Double> Mvapadrao { get; set; }
        public Nullable<Double> Aliqgeral { get; set; }
        public Nullable<int> Codprodsubkit { get; set; }
        public Nullable<int> Codconfkit { get; set; }
        public String Tipokit { get; set; }
        public Nullable<short> Codenqipient { get; set; }
        public Nullable<short> Codenqipisai { get; set; }
        public Nullable<int> Codespecst { get; set; }
        public String Visivelappos { get; set; }
        public String Utilizaendflut { get; set; }
        public Nullable<short> Maxmulteconect { get; set; }
        public Nullable<int> Qtdidentif { get; set; }
        public String Tipoidentif { get; set; }
        public Nullable<int> Codvtp { get; set; }
        public Nullable<short> Modetiqsepwms { get; set; }
        public String Impetiqsepwms { get; set; }
        public String Nroprocesso { get; set; }
        public Nullable<short> Tiposn { get; set; }
        public String Armazelote { get; set; }
        public Nullable<short> Codservtelecom { get; set; }
        public String Temrastrolote { get; set; }
        public String Codanvisa { get; set; }
        public String Descranp { get; set; }
        public Nullable<Double> Percmistglp { get; set; }
        public String Tipocontagem { get; set; }
        public Nullable<int> Codmarca { get; set; }
        public Nullable<Double> Percmistgnn { get; set; }
        public Nullable<Double> Percmistgni { get; set; }
        public Nullable<Double> Vlrpartidaglp { get; set; }
        public Nullable<int> Codctactbefd { get; set; }
        public String Codcprb { get; set; }
        public String Comercializacaoagri { get; set; }
        public Nullable<short> Obraconstcivil { get; set; }
        public Nullable<int> Classifcessaoobra { get; set; }
        public String Tipoinssespecial { get; set; }
        public Nullable<Double> Percinssespecial { get; set; }
        public String Calcdifal { get; set; }
        public Nullable<Double> Qtdagrupamentomtz { get; set; }
        public Nullable<short> Codfiltrocta { get; set; }
        public String Indescala { get; set; }
        public String Cnpjfabricante { get; set; }
        public String Codbenefnauf { get; set; }
        public String Codagregacao { get; set; }
        public String Ad_Codant { get; set; }
        public String Ad_Cartela { get; set; }
        public Nullable<int> Codidcnae { get; set; }
        public String Ad_Codcorant { get; set; }
        public String Forcaexpeconect { get; set; }
        public Nullable<Double> Ad_Gramatura { get; set; }
        public String Ad_Ca { get; set; }
        public String Registrarpeso { get; set; }
        public Nullable<Double> Ad_Custo_Ant { get; set; }
        public Nullable<int> Ad_Codcor { get; set; }
        public Nullable<short> Desviomaxtolconfsep { get; set; }
        public Nullable<short> Desviomintolconfsep { get; set; }
        public Nullable<int> Ad_Nrogrupogic { get; set; }
        public String Ad_Codreceita { get; set; }
        public String Servprestter { get; set; }
        public Nullable<Double> Ad_Qtdminima { get; set; }
        public Nullable<Double> Ad_Qtdcaixa { get; set; }
        public Nullable<Double> Ad_Larguratecido { get; set; }
        public Nullable<Double> Ad_Rendimentotecido { get; set; }
        public Nullable<Double> Ad_Gramaturalinear { get; set; }
        public String Fragmentalote { get; set; }
        public Nullable<Double> Percredbaseicmsefet { get; set; }
        public Nullable<int> Ad_Seqlotequalid { get; set; }
        public String Ad_Ld { get; set; }
        public Nullable<int> Ad_Codgrupoprod { get; set; }
        public String Ad_Bkp_Referencia { get; set; }
        public Nullable<int> Ad_Codprodfam1 { get; set; }
        public Nullable<Double> Ad_Estoque_Fiscal { get; set; }
        public Nullable<Double> Ad_Estoque_Fisico { get; set; }
        public Nullable<Double> Ad_Custo_Ultimp { get; set; }
        public String Motisencaoanvisa { get; set; }
        public Nullable<Double> Ad_Bkppeso { get; set; }
        public Nullable<int> Ad_Ldfilhoreferencia { get; set; }
        public Nullable<int> Nuversaoimg { get; set; }
        public Nullable<int> integrafox { get; set; }
        public Nullable<int> Nuversao { get; set; }
        public String Codnbs { get; set; }
        public String Consprodcat42 { get; set; }
        public Nullable<int> Ad_Codfabricante { get; set; }
        public String Ad_Componentes { get; set; }
        public String Ad_Modelo { get; set; }
        public Nullable<Double> Ad_Potnomin_A { get; set; }
        public Nullable<Double> Ad_Isc_A { get; set; }
        public Nullable<Double> Ad_Voc_A { get; set; }
        public Nullable<Double> Ad_Imp_A { get; set; }
        public Nullable<Double> Ad_Vmp_A { get; set; }
        public Nullable<Double> Ad_Pnominca_B { get; set; }
        public Nullable<Double> Ad_Pmaxcc_B { get; set; }
        public Nullable<Double> Ad_Imax_B { get; set; }
        public Nullable<Double> Ad_Iscmax_B { get; set; }
        public Nullable<Double> Ad_Imax2_B { get; set; }
        public Nullable<Double> Ad_Iscmax2_B { get; set; }
        public Nullable<Double> Ad_Vmppt_B { get; set; }
        public Nullable<Double> Ad_Vmpptmax_B { get; set; }
        public Nullable<Double> Ad_Mppt_B { get; set; }
        public Nullable<Double> Ad_Linmax1_B { get; set; }
        public Nullable<Double> Ad_Vmax_C { get; set; }
        public Nullable<Double> Ad_Imaxent_C { get; set; }
        public Nullable<Double> Ad_Imaxsai_C { get; set; }
        public Nullable<Double> Ad_Input_C { get; set; }
        public Nullable<Double> Ad_Output_C { get; set; }
        public String Ad_Alturamodulo_L { get; set; }
        public String Ad_Antichamas_E { get; set; }
        public String Ad_Antifumaca_E { get; set; }
        public String Ad_Borne_C { get; set; }
        public String Ad_Tipo_C { get; set; }
        public Nullable<Double> Ad_Classetensao_K { get; set; }
        public Nullable<Double> Ad_Conductconst_E { get; set; }
        public Nullable<Double> Ad_Conductdiameter_E { get; set; }
        public Nullable<Double> Ad_Constnxmm2_E { get; set; }
        public String Ad_Corcabo_E { get; set; }
        public Nullable<Double> Ad_Correntnom2_D { get; set; }
        public Nullable<Double> Ad_Correntnom3_D { get; set; }
        public Nullable<Double> Ad_Correntnom4_D { get; set; }
        public Nullable<Double> Ad_Correntnom_D { get; set; }
        public Nullable<Double> Ad_Currentcarring_E { get; set; }
        public Nullable<Double> Ad_Diamcabocorrentnom_D { get; set; }
        public Nullable<Double> Ad_Diamcabocorrentnom2_D { get; set; }
        public Nullable<Double> Ad_Diamcabocorrentnom3_D { get; set; }
        public Nullable<Double> Ad_Diamcabocorrentnom4_D { get; set; }
        public Nullable<Double> Ad_Diametroextern_E { get; set; }
        public Nullable<Double> Ad_Diamnomincondutor_E { get; set; }
        public String Ad_Dpsprotecac_B { get; set; }
        public String Ad_Dpsprotecdc_B { get; set; }
        public Nullable<Double> Ad_Eficiencia_A { get; set; }
        public Nullable<Double> Ad_Eficmax_B { get; set; }
        public String Ad_Embalagem_E { get; set; }
        public Nullable<Double> Ad_Espacamento_F { get; set; }
        public Nullable<Double> Ad_Espessuracapa_E { get; set; }
        public Nullable<Double> Ad_Espessuraisolam_E { get; set; }
        public Nullable<Double> Ad_Fp_B { get; set; }
        public Nullable<int> Ad_Garantia { get; set; }
        public Nullable<Double> Ad_Frequenciatrafo_K { get; set; }
        public Nullable<Double> Ad_Freqsaida_B { get; set; }
        public String Ad_Fusivel_C { get; set; }
        public Nullable<Double> Ad_Grupoligacao_K { get; set; }
        public Nullable<Double> Ad_Idescmax_C { get; set; }
        public Nullable<Double> Ad_Imax_C { get; set; }
        public Nullable<Double> Ad_Imax3_B { get; set; }
        public Nullable<Double> Ad_Imax4_B { get; set; }
        public Nullable<Double> Ad_Imax5_B { get; set; }
        public Nullable<Double> Ad_Imax6_B { get; set; }
        public Nullable<Double> Ad_Imaxsaida_B { get; set; }
        public Nullable<Double> Ad_Iscmax3_B { get; set; }
        public Nullable<Double> Ad_Iscmax4_B { get; set; }
        public Nullable<Double> Ad_Iscmax5_B { get; set; }
        public Nullable<Double> Ad_Iscmax6_B { get; set; }
        public String Ad_Materialcaixa_C { get; set; }
        public Nullable<Double> Ad_Material_F { get; set; }
        public Nullable<Double> Ad_Material_H { get; set; }
        public String Ad_Protetorsurto_C { get; set; }
        public Nullable<Double> Ad_Ncelulas_A { get; set; }
        public Nullable<Double> Ad_Outerdiameter_E { get; set; }
        public Nullable<Double> Ad_Palletcontainer_A { get; set; }
        public Nullable<Double> Ad_Pecacontainer_A { get; set; }
        public Nullable<Double> Ad_Pecapallet_A { get; set; }
        public Nullable<Double> Ad_Potaparente_B { get; set; }
        public Nullable<Double> Ad_Potencia_K { get; set; }
        public Nullable<Double> Ad_Primariotrafo_K { get; set; }
        public String Ad_Resfriamento_B { get; set; }
        public Nullable<Double> Ad_Resistencemax_E { get; set; }
        public Nullable<Double> Ad_Secundariotrafo_K { get; set; }
        public Nullable<Double> Ad_Bitolacabo_C { get; set; }
        public Nullable<Double> Ad_Secnomincond_E { get; set; }
        public Nullable<Double> Ad_Serieimaxfusivel_A { get; set; }
        public String Ad_Serie_B { get; set; }
        public Nullable<DateTime> Ad_Tamanho_H { get; set; }
        public Nullable<Double> Ad_Thdi_B { get; set; }
        public Nullable<Double> Ad_Templimite_D { get; set; }
        public Nullable<Double> Ad_Tempmx_E { get; set; }
        public Nullable<Double> Ad_Tensaooperac_C { get; set; }
        public Nullable<Double> Ad_Tensaopartida_B { get; set; }
        public Nullable<Double> Ad_Tensaosaida_B { get; set; }
        public Nullable<Double> Ad_Tensaonominal_E { get; set; }
        public Nullable<Double> Ad_Tensaonominal_D { get; set; }
        public Nullable<Double> Ad_Tensaomaxdc_B { get; set; }
        public Nullable<Double> Ad_Tensaoresivmax_C { get; set; }
        public String Ad_Tipo_L { get; set; }
        public String Ad_Tipoalim_B { get; set; }
        public Nullable<Double> Ad_Tipotelhado_F { get; set; }
        public String Ad_Tipo_A { get; set; }
        public String Ad_Seccionamento_C { get; set; }
        public Nullable<Double> Ad_Vin_K { get; set; }
        public Nullable<Double> Ad_Vout_K { get; set; }
        public Nullable<Double> Ad_Tensaomaxsistema_A { get; set; }
        public Nullable<int> Ad_Codsegmento { get; set; }
        public Nullable<Double> Incpesobruto { get; set; }
        public Nullable<Double> Incpesoliquido { get; set; }
        public Nullable<int> Nurfe { get; set; }
        public String Ad_Penvldpro { get; set; }
        public String Tipoitemsped { get; set; }
        public String Ad_Prodavo { get; set; }
        public Nullable<int> Ad_Codprodgr1 { get; set; }
        public Nullable<int> Ad_Sublimacao { get; set; }
        public String Ad_Briefing { get; set; }
        public Nullable<Double> Ad_Alturaalem { get; set; }
        public Nullable<Double> Ad_Larguraalem { get; set; }
        public Nullable<Double> Ad_Espessuraalem { get; set; }
        public Nullable<Double> Ad_Comprimentoalem { get; set; }
        public Nullable<Double> Ad_Capacidadealem { get; set; }
        public Nullable<Double> Ad_Pesoalem { get; set; }
        public Nullable<Double> Mvaoriginaldrcst { get; set; }
        public Nullable<Double> Tamanhomediopeca { get; set; }
        public Nullable<int> Idgrade { get; set; }
        public Nullable<Double> Percentseppul { get; set; }
        public String Ad_Img_Estmp { get; set; }
        public Nullable<int> Ad_Qtdcntr20 { get; set; }
        public Nullable<int> Ad_Qtdcntr40 { get; set; }
        public String Ad_Cadprodimportacao { get; set; }
        public String Ad_Prodreclass { get; set; }
        public Nullable<int> Ad_Prodreclassref { get; set; }
        public String Atunuversao { get; set; }
        public String Gradepadrao { get; set; }
        public String Obtstantmedent { get; set; }
        public String Descproddrcst { get; set; }
        public Nullable<Double> Aliqfethab { get; set; }
        public String Codvolfethab { get; set; }
        public Nullable<Double> Aliqinternacat42 { get; set; }
        public String Participaadrcst { get; set; }
        public Nullable<Double> Mvaoriginaladrcst { get; set; }
        public Nullable<Double> Aliqfecop { get; set; }
        public String Prodsujfecop { get; set; }
        public String Desdesccalcpis { get; set; }
        public Nullable<int> Ad_Codcarprod { get; set; }
        public Nullable<int> Ad_Coddirvdprod { get; set; }
        public Nullable<int> Ad_Codsegprod { get; set; }
        public String Gerimpnretreinfaq { get; set; }
        public Nullable<int> Ad_Codsegamprod { get; set; }
        public String Conestorigprod { get; set; }
        public String Prodinterno { get; set; }
        public String Prodaliadrcst { get; set; }
        public Nullable<short> Tiputilcom { get; set; }
        public String Calcfustpro { get; set; }
        public String Calcfunttelpro { get; set; }
        public String Codbardifgtin { get; set; }
        public String Codbartribdifgtin { get; set; }


    }
}
