using System;

namespace back.domain.entities
{
    public interface ITSIEMP
    {
        public short CODEMP { get; set; }
        public string NOMEFANTASIA { get; set; }
        public string RAZAOSOCIAL { get; set; }
        public string RAZAOABREV { get; set; }
        public Nullable<short> CODEMPMATRIZ { get; set; }
        public Nullable<int> CODEND { get; set; }
        public string NUMEND { get; set; }
        public string COMPLEMENTO { get; set; }
        public int CODBAI { get; set; }
        public Nullable<int> CODCID { get; set; }
        public string CEP { get; set; }
        public string TELEFONE { get; set; }
        public string FAX { get; set; }
        public string TELEX { get; set; }
        public string EMAIL { get; set; }
        public string HOMEPAGE { get; set; }
        public Nullable<short> NUMPROPR { get; set; }
        public string PRINCTITULAR { get; set; }
        public string CGC { get; set; }
        public string INSCESTAD { get; set; }
        public string INSCMUN { get; set; }
        public Nullable<int> CODMUN { get; set; }
        public Nullable<short> NATESTAB { get; set; }
        public Nullable<short> NATJUR { get; set; }
        public string RAMOATIV { get; set; }
        public Nullable<int> ATIVECON { get; set; }
        public string REGJUNTACOM { get; set; }
        public Nullable<System.DateTime> DTREGJUNTA { get; set; }
        public byte[] LOGOMARCA { get; set; }
        public string FINANCEIRO { get; set; }
        public string ESTOQUE { get; set; }
        public string CARGAS { get; set; }
        public string COMISSOES { get; set; }
        public string PRODUCAO { get; set; }
        public string SUPDECISAO { get; set; }
        public string LIVROSFISCAIS { get; set; }
        public Nullable<System.DateTime> CONTABILIDADE { get; set; }
        public string FOLHAPAGTO { get; set; }
        public string CODCNL { get; set; }
        public string SIMPLES { get; set; }
        public int CODPARC { get; set; }
        public Nullable<double> LIMCURVA_B { get; set; }
        public Nullable<double> LIMCURVA_C { get; set; }
        public Nullable<short> EMPAGRUPARGOL { get; set; }
        public string SERIENFDES { get; set; }
        public string MODELONFDES { get; set; }
        public string COOPERATIVA { get; set; }
        public Nullable<System.DateTime> DTCONVSOC { get; set; }
        public string DUPLIV { get; set; }
        public string CPFRESP { get; set; }
        public Nullable<short> CODREGTRIB { get; set; }
        public Nullable<int> TIPOSN { get; set; }
        public int CODPARCDIV { get; set; }
        public string MD5PAF { get; set; }
        public string RAZAOSOCIALCOMPLETA { get; set; }
        public string LATITUDE { get; set; }
        public string LONGITUDE { get; set; }
        public string SIMPLESNACNAUF { get; set; }
        public string DMACODINSP { get; set; }
        public string DMAESPECIAL { get; set; }
        public Nullable<System.DateTime> DTENCERBALAN { get; set; }
        public string SERVIDORSMTP { get; set; }
        public string TIPOSMTP { get; set; }
        public string USUARIOSMTP { get; set; }
        public string SENHASMTP { get; set; }
        public short PORTASMTP { get; set; }
        public string SEGURANCASMTP { get; set; }
        public string CODQUALASSIN { get; set; }
        public Nullable<int> CODPARCRESP { get; set; }
        public string SITESPECIALRESP { get; set; }
        public string EXIGEISSQN { get; set; }
        public string REGESPTRIBUT { get; set; }
        public string RNTRC { get; set; }
        public Nullable<short> CLASSTRIB { get; set; }
        public Nullable<int> CNAEPREPON { get; set; }
        public short INDCOOP { get; set; }
        public short INDCONSTR { get; set; }
        public Nullable<short> INFOOBRA { get; set; }
        public Nullable<short> CODUSU { get; set; }
        public System.DateTime DHALTER { get; set; }
        public Nullable<short> ACDINTISENMULTA { get; set; }
        public Nullable<int> CODPARCEMPSOFT { get; set; }
        public Nullable<int> CODCTTPARCEMPSOFT { get; set; }
        public short INDSITESP { get; set; }
        public Nullable<int> COREMPRESA { get; set; }
        public Nullable<int> QTDACESSOS { get; set; }
        public string ENVESOCIAL { get; set; }
        public string RECIBOESOCIAL { get; set; }
        public Nullable<System.DateTime> INIVALESOCIAL { get; set; }
        public Nullable<System.DateTime> FIMVALESOCIAL { get; set; }
        public Nullable<int> AD_PARCCR { get; set; }
        public string AD_TRIBUTA { get; set; }
        public string AD_QUALIFI { get; set; }
        public string AD_CRIVARM { get; set; }
        public string AD_REGPIS { get; set; }
        public byte[] AD_IMAGEM { get; set; }
        public Nullable<short> INDOPCCP { get; set; }
        public string AD_IGNORAAGLUTINACAO { get; set; }
        public Nullable<int> AD_MODEVP { get; set; }
        public Nullable<int> AD_NURBVP { get; set; }
        public Nullable<int> AD_TOPPEDREAL { get; set; }
        public Nullable<int> AD_TOPPEDVIRT { get; set; }
        public Nullable<int> AD_TOPENTVIRT { get; set; }
        public Nullable<int> AD_TOPENTREAL { get; set; }
        public Nullable<int> AD_CONFERENCIA { get; set; }
        public Nullable<int> AD_TOPDESPADT { get; set; }
        public Nullable<int> NUVERSAO { get; set; }
        public string USARAZAOSOCIAL { get; set; }
        public Nullable<System.DateTime> DTABERTURA { get; set; }
        public string EMPIDENOTAS { get; set; }
        public string PRODUTORRURAL { get; set; }
        public string COTM { get; set; }
    }
}
