using back.domain.entities;
using System;

namespace back.domain.DTO.TSIEMP
{
    public class TSIEMPDTOUpdateDTO : ITSIEMP
    {
        public short CODEMP { get; set; }
        public string NOMEFANTASIA { get; set; }
        public string RAZAOSOCIAL { get; set; }
        public string RAZAOABREV { get; set; }
        public short? CODEMPMATRIZ { get; set; }
        public int? CODEND { get; set; }
        public string NUMEND { get; set; }
        public string COMPLEMENTO { get; set; }
        public int CODBAI { get; set; }
        public int? CODCID { get; set; }
        public string CEP { get; set; }
        public string TELEFONE { get; set; }
        public string FAX { get; set; }
        public string TELEX { get; set; }
        public string EMAIL { get; set; }
        public string HOMEPAGE { get; set; }
        public short? NUMPROPR { get; set; }
        public string PRINCTITULAR { get; set; }
        public string CGC { get; set; }
        public string INSCESTAD { get; set; }
        public string INSCMUN { get; set; }
        public int? CODMUN { get; set; }
        public short? NATESTAB { get; set; }
        public short? NATJUR { get; set; }
        public string RAMOATIV { get; set; }
        public int? ATIVECON { get; set; }
        public string REGJUNTACOM { get; set; }
        public DateTime? DTREGJUNTA { get; set; }
        public byte[] LOGOMARCA { get; set; }
        public string FINANCEIRO { get; set; }
        public string ESTOQUE { get; set; }
        public string CARGAS { get; set; }
        public string COMISSOES { get; set; }
        public string PRODUCAO { get; set; }
        public string SUPDECISAO { get; set; }
        public string LIVROSFISCAIS { get; set; }
        public DateTime? CONTABILIDADE { get; set; }
        public string FOLHAPAGTO { get; set; }
        public string CODCNL { get; set; }
        public string SIMPLES { get; set; }
        public int CODPARC { get; set; }
        public double? LIMCURVA_B { get; set; }
        public double? LIMCURVA_C { get; set; }
        public short? EMPAGRUPARGOL { get; set; }
        public string SERIENFDES { get; set; }
        public string MODELONFDES { get; set; }
        public string COOPERATIVA { get; set; }
        public DateTime? DTCONVSOC { get; set; }
        public string DUPLIV { get; set; }
        public string CPFRESP { get; set; }
        public short? CODREGTRIB { get; set; }
        public int? TIPOSN { get; set; }
        public int CODPARCDIV { get; set; }
        public string MD5PAF { get; set; }
        public string RAZAOSOCIALCOMPLETA { get; set; }
        public string LATITUDE { get; set; }
        public string LONGITUDE { get; set; }
        public string SIMPLESNACNAUF { get; set; }
        public string DMACODINSP { get; set; }
        public string DMAESPECIAL { get; set; }
        public DateTime? DTENCERBALAN { get; set; }
        public string SERVIDORSMTP { get; set; }
        public string TIPOSMTP { get; set; }
        public string USUARIOSMTP { get; set; }
        public string SENHASMTP { get; set; }
        public short PORTASMTP { get; set; }
        public string SEGURANCASMTP { get; set; }
        public string CODQUALASSIN { get; set; }
        public int? CODPARCRESP { get; set; }
        public string SITESPECIALRESP { get; set; }
        public string EXIGEISSQN { get; set; }
        public string REGESPTRIBUT { get; set; }
        public string RNTRC { get; set; }
        public short? CLASSTRIB { get; set; }
        public int? CNAEPREPON { get; set; }
        public short INDCOOP { get; set; }
        public short INDCONSTR { get; set; }
        public short? INFOOBRA { get; set; }
        public short? CODUSU { get; set; }
        public DateTime DHALTER { get; set; }
        public short? ACDINTISENMULTA { get; set; }
        public int? CODPARCEMPSOFT { get; set; }
        public int? CODCTTPARCEMPSOFT { get; set; }
        public short INDSITESP { get; set; }
        public int? COREMPRESA { get; set; }
        public int? QTDACESSOS { get; set; }
        public string ENVESOCIAL { get; set; }
        public string RECIBOESOCIAL { get; set; }
        public DateTime? INIVALESOCIAL { get; set; }
        public DateTime? FIMVALESOCIAL { get; set; }
        public int? AD_PARCCR { get; set; }
        public string AD_TRIBUTA { get; set; }
        public string AD_QUALIFI { get; set; }
        public string AD_CRIVARM { get; set; }
        public string AD_REGPIS { get; set; }
        public byte[] AD_IMAGEM { get; set; }
        public short? INDOPCCP { get; set; }
        public string AD_IGNORAAGLUTINACAO { get; set; }
        public int? AD_MODEVP { get; set; }
        public int? AD_NURBVP { get; set; }
        public int? AD_TOPPEDREAL { get; set; }
        public int? AD_TOPPEDVIRT { get; set; }
        public int? AD_TOPENTVIRT { get; set; }
        public int? AD_TOPENTREAL { get; set; }
        public int? AD_CONFERENCIA { get; set; }
        public int? AD_TOPDESPADT { get; set; }
        public int? NUVERSAO { get; set; }
        public string USARAZAOSOCIAL { get; set; }
        public DateTime? DTABERTURA { get; set; }
        public string EMPIDENOTAS { get; set; }
        public string PRODUTORRURAL { get; set; }
        public string COTM { get; set; }
    }
}
