using back.domain.entities;
using System;

namespace back.domain.DTO.TGFPRO
{
    public class TGFPRODTOUpdateDTO : ITGFPRO
    {
        public int CodProd { get; set; }
        public string Descrprod { get; set; }
        public string Compldesc { get; set; }
        public string Caracteristicas { get; set; }
        public string Referencia { get; set; }
        public int Codgrupoprod { get; set; }
        public string Codvol { get; set; }
        public string Marca { get; set; }
        public string Localizacao { get; set; }
        public short? Codipi { get; set; }
        public short? Classubtrib { get; set; }
        public short? Codformprec { get; set; }
        public double? Marglucro { get; set; }
        public double? Multipvenda { get; set; }
        public short? Deccusto { get; set; }
        public short? Decvlr { get; set; }
        public short? Decqtd { get; set; }
        public double? Comger { get; set; }
        public double? Comvend { get; set; }
        public double? Descmax { get; set; }
        public decimal Pesobruto { get; set; }
        public decimal Pesoliq { get; set; }
        public double? Medaux { get; set; }
        public short? Prazoval { get; set; }
        public decimal? Agrupmin { get; set; }
        public short? Qtdemb { get; set; }
        public string Alertaestmin { get; set; }
        public string Promocao { get; set; }
        public string Temicms { get; set; }
        public string Temiss { get; set; }
        public string Temipivenda { get; set; }
        public string Temipicompra { get; set; }
        public string Temirf { get; set; }
        public double? Percirf { get; set; }
        public string Teminss { get; set; }
        public double Percinss { get; set; }
        public double Redbaseinss { get; set; }
        public string Usoprod { get; set; }
        public string Origprod { get; set; }
        public string Tipsubst { get; set; }
        public double? Codicmsfast { get; set; }
        public string Tiplancnota { get; set; }
        public string Tipcontest { get; set; }
        public short? Codtab { get; set; }
        public int? Codctactb { get; set; }
        public byte[] Imagem { get; set; }
        public string Ativo { get; set; }
        public double? Estmax { get; set; }
        public double? Estmin { get; set; }
        public string Apresdetalhe { get; set; }
        public string Selecionado { get; set; }
        public string Titcontest { get; set; }
        public string Liscontest { get; set; }
        public int? Grupoicms { get; set; }
        public decimal? Percaumentcusto { get; set; }
        public string Local { get; set; }
        public short Codmoeda { get; set; }
        public DateTime Dtalter { get; set; }
        public string Usalocal { get; set; }
        public string Homepage { get; set; }
        public int? Codctactb2 { get; set; }
        public int? Codctactb3 { get; set; }
        public DateTime? Temposerv { get; set; }
        public string Endimagem { get; set; }
        public short Codusu { get; set; }
        public int? Codparcforn { get; set; }
        public string Codvolcompra { get; set; }
        public string Codprodroi { get; set; }
        public string Grupodescprod { get; set; }
        public string Refforn { get; set; }
        public string Hrdobrada { get; set; }
        public string Icmsgerencia { get; set; }
        public int Codnat { get; set; }
        public int Codcencus { get; set; }
        public int Codproj { get; set; }
        public double? M3 { get; set; }
        public string Temciap { get; set; }
        public string Implaudolote { get; set; }
        public int? Codgar { get; set; }
        public int? Codctactb4 { get; set; }
        public string Dimensoes { get; set; }
        public double? Percquebratec { get; set; }
        public short? Codfiltro { get; set; }
        public string Endmodrotulo { get; set; }
        public int? Codgenero { get; set; }
        public int? Codlst { get; set; }
        public string Padrao { get; set; }
        public string Naturezaoperdes { get; set; }
        public int? Cnae { get; set; }
        public string Solcompra { get; set; }
        public string Confere { get; set; }
        public string Remeter { get; set; }
        public string Motivoincexc { get; set; }
        public decimal? Arredpreco { get; set; }
        public string Temcomissao { get; set; }
        public string Componobrig { get; set; }
        public string Fattotal { get; set; }
        public string Nometab { get; set; }
        public string Ap1rctego { get; set; }
        public string Calculogiro { get; set; }
        public double? Redbaseirf { get; set; }
        public double? Altura { get; set; }
        public double? Largura { get; set; }
        public double? Espessura { get; set; }
        public string Unidade { get; set; }
        public short? Codformaponta { get; set; }
        public short? Codcos { get; set; }
        public string Confcegapeso { get; set; }
        public short? Ordcalccustprod { get; set; }
        public string Regrawms { get; set; }
        public string Grupopis { get; set; }
        public string Grupocofins { get; set; }
        public string Grupocssl { get; set; }
        public short? Cstipient { get; set; }
        public short? Cstipisai { get; set; }
        public string Statusincexc { get; set; }
        public string Utilizawms { get; set; }
        public string Balanca { get; set; }
        public short? Codpais { get; set; }
        public string Rendimento { get; set; }
        public string Obsetiqueta { get; set; }
        public int? Codanp { get; set; }
        public string Codautcodif { get; set; }
        public int? Codprodagrupapt { get; set; }
        public int? Codprodagrupaptenc { get; set; }
        public string Cultura { get; set; }
        public string Cientifico { get; set; }
        public int? Classeagt { get; set; }
        public int? Grupoquimico { get; set; }
        public int? Classetox { get; set; }
        public int? Princativo { get; set; }
        public string Formulacao { get; set; }
        public string Concentracao { get; set; }
        public string Modoaplic { get; set; }
        public string Epocaaplic { get; set; }
        public string Manejoint { get; set; }
        public double? Dosagem { get; set; }
        public string Voldosagem { get; set; }
        public double? Dosagempor { get; set; }
        public string Voldosagempor { get; set; }
        public string Rendimentopr { get; set; }
        public string Receituario { get; set; }
        public string Exigebenefic { get; set; }
        public string Tipoclasseagt { get; set; }
        public string Tipogrupoquimico { get; set; }
        public string Tipoprincativo { get; set; }
        public string Tipoclassetox { get; set; }
        public int? Grupotransg { get; set; }
        public string Geraplaprod { get; set; }
        public int? Aplicacao { get; set; }
        public int? intervalo { get; set; }
        public int? Carencia { get; set; }
        public double? Rendimentoha { get; set; }
        public short Produtonfe { get; set; }
        public short Tipgtinnfe { get; set; }
        public string Ncm { get; set; }
        public string Codvolplan { get; set; }
        public double? Descmaxflex { get; set; }
        public double? Acrescmax { get; set; }
        public string Flex { get; set; }
        public int? Numitemrea { get; set; }
        public string Imprimir { get; set; }
        public string Confirmaimp { get; set; }
        public string Apuraprodepe { get; set; }
        public string Indespprodepe { get; set; }
        public int Qtdnflaudosint { get; set; }
        public string Codtribmuniss { get; set; }
        public string Tipcontestwms { get; set; }
        public string Listalpm { get; set; }
        public string Oneroso { get; set; }
        public string Refmercmed { get; set; }
        public string Termolabil { get; set; }
        public double? Tempminima { get; set; }
        public double? Tempmaxima { get; set; }
        public string Controlado { get; set; }
        public string Idenportaria { get; set; }
        public string Idenotc { get; set; }
        public string Idencorrelato { get; set; }
        public string Idencosme { get; set; }
        public string Prodfalta { get; set; }
        public int? Codfab { get; set; }
        public int Statusmed { get; set; }
        public int? Codcpr { get; set; }
        public short? Seqspr { get; set; }
        public short? Seqsca { get; set; }
        public short? Seqste { get; set; }
        public int? Codcat { get; set; }
        public int? Codter { get; set; }
        public int? Codpat { get; set; }
        public double Mvaajustado { get; set; }
        public string Infpureza { get; set; }
        public string Fabricante { get; set; }
        public string Usastatuslote { get; set; }
        public short? Tamlote { get; set; }
        public short? Tamserie { get; set; }
        public string Unidminarmaz { get; set; }
        public string Origemfat { get; set; }
        public string Usacodbarrasqtd { get; set; }
        public string Md5paf { get; set; }
        public string Valcapm3 { get; set; }
        public string Qtdpecafrac { get; set; }
        public string Utilordcorte { get; set; }
        public int? Codprodperda { get; set; }
        public string Descrutilbem { get; set; }
        public string Impordemcorte { get; set; }
        public double Perctroca { get; set; }
        public int? Corfontconspreco { get; set; }
        public int? Corfundoconspreco { get; set; }
        public string Codvolres { get; set; }
        public int? Codareasep { get; set; }
        public short? Identimob { get; set; }
        public short? Utilimob { get; set; }
        public string Temcredpiscofinsdepr { get; set; }
        public int? Codprodinnatura { get; set; }
        public string Utilsmartcard { get; set; }
        public string Recupavaria { get; set; }
        public double? Convervol { get; set; }
        public int? Lastro { get; set; }
        public int? Camadas { get; set; }
        public double? Ordemmedida { get; set; }
        public double? Aliqicmsintefd { get; set; }
        public string Codregmapa { get; set; }
        public string Apresform { get; set; }
        public string Codbarcomp { get; set; }
        public string Temmedicao { get; set; }
        public short? Codfiltroreq { get; set; }
        public string Natbcpiscofins { get; set; }
        public string Contarporpeso { get; set; }
        public int? Codlocalpadrao { get; set; }
        public string Permcompprod { get; set; }
        public short Codexncm { get; set; }
        public int Qtdcst { get; set; }
        public int Diascst { get; set; }
        public int Perctolvarcst { get; set; }
        public double? Qtdpedpend { get; set; }
        public int? Leadtime { get; set; }
        public string Valcbglobal { get; set; }
        public string Usapontos { get; set; }
        public int? Codrfa { get; set; }
        public decimal? Percroyalty { get; set; }
        public string integraeconect { get; set; }
        public int? Shelflife { get; set; }
        public int? Shelflifemin { get; set; }
        public string Dtvaldif { get; set; }
        public string Enqreintegra { get; set; }
        public int? Diasexpedicao { get; set; }
        public string Codbarbalanca { get; set; }
        public double Perccmtnac { get; set; }
        public double Perccmtimp { get; set; }
        public string Notifconf { get; set; }
        public string Usaseriefab { get; set; }
        public string Tipsernfe { get; set; }
        public string Vencompindiv { get; set; }
        public string Excluirconf { get; set; }
        public string Produzaut { get; set; }
        public string Usaimpagrupmin { get; set; }
        public string Rastrestoque { get; set; }
        public string Impetiqconf { get; set; }
        public double? Vlrcomerc { get; set; }
        public double? Vlrparcimpext { get; set; }
        public string Codfci { get; set; }
        public string Codativreintegra { get; set; }
        public string Servparaindust { get; set; }
        public string Cat1799spres { get; set; }
        public double? Aliqnac { get; set; }
        public double? Aliqimp { get; set; }
        public string Descrprodnfe { get; set; }
        public string Geracustcompseg { get; set; }
        public double Estsegqtd { get; set; }
        public short? Estsegdias { get; set; }
        public DateTime? Dtalteresq { get; set; }
        public short? Lotecompras { get; set; }
        public double Estmaxqtd { get; set; }
        public short? Estmaxdias { get; set; }
        public DateTime? Dtalteremq { get; set; }
        public double Desviomax { get; set; }
        public double Arredagrup { get; set; }
        public string Aplicasazo { get; set; }
        public double Lotecompminimo { get; set; }
        public double Agrupcompminimo { get; set; }
        public string Usaseriesepwms { get; set; }
        public int? Codgprod { get; set; }
        public int? Codparcconsig { get; set; }
        public short? Topfaturcon { get; set; }
        public string Serfaturcon { get; set; }
        public string Usalotedtval { get; set; }
        public string Usalotedtfab { get; set; }
        public string Exigelastrocamadas { get; set; }
        public string Fixoagenda { get; set; }
        public string Exibcompexpkit { get; set; }
        public short? Tiporeceitamod21 { get; set; }
        public short? Natefdcontm410m810 { get; set; }
        public int? Codprodsubst { get; set; }
        public DateTime? Dtsubst { get; set; }
        public int? Codcomp { get; set; }
        public double? Perctolpesomaior { get; set; }
        public double? Perctolpesomenor { get; set; }
        public string Codvolpesovar { get; set; }
        public string Usacontpesovar { get; set; }
        public double? Perctolpesomaiorsep { get; set; }
        public double? Perctolpesomenorsep { get; set; }
        public double? Pct_Bf { get; set; }
        public short? Prz_Bf { get; set; }
        public string Controlmedic { get; set; }
        public short? Decvlrent { get; set; }
        public double Perccmtfed { get; set; }
        public double Perccmtest { get; set; }
        public double Perccmtmun { get; set; }
        public string Descvenconsul { get; set; }
        public int? Grupoicms2 { get; set; }
        public double? Mvapadrao { get; set; }
        public double? Aliqgeral { get; set; }
        public int? Codprodsubkit { get; set; }
        public int? Codconfkit { get; set; }
        public string Tipokit { get; set; }
        public short? Codenqipient { get; set; }
        public short? Codenqipisai { get; set; }
        public int? Codespecst { get; set; }
        public string Visivelappos { get; set; }
        public string Utilizaendflut { get; set; }
        public short? Maxmulteconect { get; set; }
        public int? Qtdidentif { get; set; }
        public string Tipoidentif { get; set; }
        public int? Codvtp { get; set; }
        public short? Modetiqsepwms { get; set; }
        public string Impetiqsepwms { get; set; }
        public string Nroprocesso { get; set; }
        public short? Tiposn { get; set; }
        public string Armazelote { get; set; }
        public short? Codservtelecom { get; set; }
        public string Temrastrolote { get; set; }
        public string Codanvisa { get; set; }
        public string Descranp { get; set; }
        public double? Percmistglp { get; set; }
        public string Tipocontagem { get; set; }
        public int? Codmarca { get; set; }
        public double? Percmistgnn { get; set; }
        public double? Percmistgni { get; set; }
        public double? Vlrpartidaglp { get; set; }
        public int? Codctactbefd { get; set; }
        public string Codcprb { get; set; }
        public string Comercializacaoagri { get; set; }
        public short? Obraconstcivil { get; set; }
        public int? Classifcessaoobra { get; set; }
        public string Tipoinssespecial { get; set; }
        public double? Percinssespecial { get; set; }
        public string Calcdifal { get; set; }
        public double? Qtdagrupamentomtz { get; set; }
        public short? Codfiltrocta { get; set; }
        public string Indescala { get; set; }
        public string Cnpjfabricante { get; set; }
        public string Codbenefnauf { get; set; }
        public string Codagregacao { get; set; }
        public string Ad_Codant { get; set; }
        public string Ad_Cartela { get; set; }
        public int? Codidcnae { get; set; }
        public string Ad_Codcorant { get; set; }
        public string Forcaexpeconect { get; set; }
        public double? Ad_Gramatura { get; set; }
        public string Ad_Ca { get; set; }
        public string Registrarpeso { get; set; }
        public double? Ad_Custo_Ant { get; set; }
        public int? Ad_Codcor { get; set; }
        public short? Desviomaxtolconfsep { get; set; }
        public short? Desviomintolconfsep { get; set; }
        public int? Ad_Nrogrupogic { get; set; }
        public string Ad_Codreceita { get; set; }
        public string Servprestter { get; set; }
        public double? Ad_Qtdminima { get; set; }
        public double? Ad_Qtdcaixa { get; set; }
        public double? Ad_Larguratecido { get; set; }
        public double? Ad_Rendimentotecido { get; set; }
        public double? Ad_Gramaturalinear { get; set; }
        public string Fragmentalote { get; set; }
        public double? Percredbaseicmsefet { get; set; }
        public int? Ad_Seqlotequalid { get; set; }
        public string Ad_Ld { get; set; }
        public int? Ad_Codgrupoprod { get; set; }
        public string Ad_Bkp_Referencia { get; set; }
        public int? Ad_Codprodfam1 { get; set; }
        public double? Ad_Estoque_Fiscal { get; set; }
        public double? Ad_Estoque_Fisico { get; set; }
        public double? Ad_Custo_Ultimp { get; set; }
        public string Motisencaoanvisa { get; set; }
        public double? Ad_Bkppeso { get; set; }
        public int? Ad_Ldfilhoreferencia { get; set; }
        public int? Nuversaoimg { get; set; }
        public int? integrafox { get; set; }
        public int? Nuversao { get; set; }
        public string Codnbs { get; set; }
        public string Consprodcat42 { get; set; }
        public int? Ad_Codfabricante { get; set; }
        public string Ad_Componentes { get; set; }
        public string Ad_Modelo { get; set; }
        public double? Ad_Potnomin_A { get; set; }
        public double? Ad_Isc_A { get; set; }
        public double? Ad_Voc_A { get; set; }
        public double? Ad_Imp_A { get; set; }
        public double? Ad_Vmp_A { get; set; }
        public double? Ad_Pnominca_B { get; set; }
        public double? Ad_Pmaxcc_B { get; set; }
        public double? Ad_Imax_B { get; set; }
        public double? Ad_Iscmax_B { get; set; }
        public double? Ad_Imax2_B { get; set; }
        public double? Ad_Iscmax2_B { get; set; }
        public double? Ad_Vmppt_B { get; set; }
        public double? Ad_Vmpptmax_B { get; set; }
        public double? Ad_Mppt_B { get; set; }
        public double? Ad_Linmax1_B { get; set; }
        public double? Ad_Vmax_C { get; set; }
        public double? Ad_Imaxent_C { get; set; }
        public double? Ad_Imaxsai_C { get; set; }
        public double? Ad_Input_C { get; set; }
        public double? Ad_Output_C { get; set; }
        public string Ad_Alturamodulo_L { get; set; }
        public string Ad_Antichamas_E { get; set; }
        public string Ad_Antifumaca_E { get; set; }
        public string Ad_Borne_C { get; set; }
        public string Ad_Tipo_C { get; set; }
        public double? Ad_Classetensao_K { get; set; }
        public double? Ad_Conductconst_E { get; set; }
        public double? Ad_Conductdiameter_E { get; set; }
        public double? Ad_Constnxmm2_E { get; set; }
        public string Ad_Corcabo_E { get; set; }
        public double? Ad_Correntnom2_D { get; set; }
        public double? Ad_Correntnom3_D { get; set; }
        public double? Ad_Correntnom4_D { get; set; }
        public double? Ad_Correntnom_D { get; set; }
        public double? Ad_Currentcarring_E { get; set; }
        public double? Ad_Diamcabocorrentnom_D { get; set; }
        public double? Ad_Diamcabocorrentnom2_D { get; set; }
        public double? Ad_Diamcabocorrentnom3_D { get; set; }
        public double? Ad_Diamcabocorrentnom4_D { get; set; }
        public double? Ad_Diametroextern_E { get; set; }
        public double? Ad_Diamnomincondutor_E { get; set; }
        public string Ad_Dpsprotecac_B { get; set; }
        public string Ad_Dpsprotecdc_B { get; set; }
        public double? Ad_Eficiencia_A { get; set; }
        public double? Ad_Eficmax_B { get; set; }
        public string Ad_Embalagem_E { get; set; }
        public double? Ad_Espacamento_F { get; set; }
        public double? Ad_Espessuracapa_E { get; set; }
        public double? Ad_Espessuraisolam_E { get; set; }
        public double? Ad_Fp_B { get; set; }
        public int? Ad_Garantia { get; set; }
        public double? Ad_Frequenciatrafo_K { get; set; }
        public double? Ad_Freqsaida_B { get; set; }
        public string Ad_Fusivel_C { get; set; }
        public double? Ad_Grupoligacao_K { get; set; }
        public double? Ad_Idescmax_C { get; set; }
        public double? Ad_Imax_C { get; set; }
        public double? Ad_Imax3_B { get; set; }
        public double? Ad_Imax4_B { get; set; }
        public double? Ad_Imax5_B { get; set; }
        public double? Ad_Imax6_B { get; set; }
        public double? Ad_Imaxsaida_B { get; set; }
        public double? Ad_Iscmax3_B { get; set; }
        public double? Ad_Iscmax4_B { get; set; }
        public double? Ad_Iscmax5_B { get; set; }
        public double? Ad_Iscmax6_B { get; set; }
        public string Ad_Materialcaixa_C { get; set; }
        public double? Ad_Material_F { get; set; }
        public double? Ad_Material_H { get; set; }
        public string Ad_Protetorsurto_C { get; set; }
        public double? Ad_Ncelulas_A { get; set; }
        public double? Ad_Outerdiameter_E { get; set; }
        public double? Ad_Palletcontainer_A { get; set; }
        public double? Ad_Pecacontainer_A { get; set; }
        public double? Ad_Pecapallet_A { get; set; }
        public double? Ad_Potaparente_B { get; set; }
        public double? Ad_Potencia_K { get; set; }
        public double? Ad_Primariotrafo_K { get; set; }
        public string Ad_Resfriamento_B { get; set; }
        public double? Ad_Resistencemax_E { get; set; }
        public double? Ad_Secundariotrafo_K { get; set; }
        public double? Ad_Bitolacabo_C { get; set; }
        public double? Ad_Secnomincond_E { get; set; }
        public double? Ad_Serieimaxfusivel_A { get; set; }
        public string Ad_Serie_B { get; set; }
        public DateTime? Ad_Tamanho_H { get; set; }
        public double? Ad_Thdi_B { get; set; }
        public double? Ad_Templimite_D { get; set; }
        public double? Ad_Tempmx_E { get; set; }
        public double? Ad_Tensaooperac_C { get; set; }
        public double? Ad_Tensaopartida_B { get; set; }
        public double? Ad_Tensaosaida_B { get; set; }
        public double? Ad_Tensaonominal_E { get; set; }
        public double? Ad_Tensaonominal_D { get; set; }
        public double? Ad_Tensaomaxdc_B { get; set; }
        public double? Ad_Tensaoresivmax_C { get; set; }
        public string Ad_Tipo_L { get; set; }
        public string Ad_Tipoalim_B { get; set; }
        public double? Ad_Tipotelhado_F { get; set; }
        public string Ad_Tipo_A { get; set; }
        public string Ad_Seccionamento_C { get; set; }
        public double? Ad_Vin_K { get; set; }
        public double? Ad_Vout_K { get; set; }
        public double? Ad_Tensaomaxsistema_A { get; set; }
        public int? Ad_Codsegmento { get; set; }
        public double? Incpesobruto { get; set; }
        public double? Incpesoliquido { get; set; }
        public int? Nurfe { get; set; }
        public string Ad_Penvldpro { get; set; }
        public string Tipoitemsped { get; set; }
        public string Ad_Prodavo { get; set; }
        public int? Ad_Codprodgr1 { get; set; }
        public int? Ad_Sublimacao { get; set; }
        public string Ad_Briefing { get; set; }
        public double? Ad_Alturaalem { get; set; }
        public double? Ad_Larguraalem { get; set; }
        public double? Ad_Espessuraalem { get; set; }
        public double? Ad_Comprimentoalem { get; set; }
        public double? Ad_Capacidadealem { get; set; }
        public double? Ad_Pesoalem { get; set; }
        public double? Mvaoriginaldrcst { get; set; }
        public double? Tamanhomediopeca { get; set; }
        public int? Idgrade { get; set; }
        public double? Percentseppul { get; set; }
        public string Ad_Img_Estmp { get; set; }
        public int? Ad_Qtdcntr20 { get; set; }
        public int? Ad_Qtdcntr40 { get; set; }
        public string Ad_Cadprodimportacao { get; set; }
        public string Ad_Prodreclass { get; set; }
        public int? Ad_Prodreclassref { get; set; }
        public string Atunuversao { get; set; }
        public string Gradepadrao { get; set; }
        public string Obtstantmedent { get; set; }
        public string Descproddrcst { get; set; }
        public double? Aliqfethab { get; set; }
        public string Codvolfethab { get; set; }
        public double? Aliqinternacat42 { get; set; }
        public string Participaadrcst { get; set; }
        public double? Mvaoriginaladrcst { get; set; }
        public double? Aliqfecop { get; set; }
        public string Prodsujfecop { get; set; }
        public string Desdesccalcpis { get; set; }
        public int? Ad_Codcarprod { get; set; }
        public int? Ad_Coddirvdprod { get; set; }
        public int? Ad_Codsegprod { get; set; }
        public string Gerimpnretreinfaq { get; set; }
        public int? Ad_Codsegamprod { get; set; }
        public string Conestorigprod { get; set; }
        public string Prodinterno { get; set; }
        public string Prodaliadrcst { get; set; }
        public short? Tiputilcom { get; set; }
        public string Calcfustpro { get; set; }
        public string Calcfunttelpro { get; set; }
        public string Codbardifgtin { get; set; }
        public string Codbartribdifgtin { get; set; }
    }
}
